apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "akka-demo"
---
apiVersion: "akka.lightbend.com/v1"
kind: "AkkaMicroservice"
metadata:
  name: "shopping-cart-service"
  namespace: "akka-demo"
spec:
  replicas: 3
  image: "docker.io/patriknw/shopping-cart-service:20201124-120910-e6028e0"
  imagePullPolicy: "IfNotPresent"
  appVersion: "20201124-120910"
  imagePullSecrets:
  - "regcred"
  splitBrainResolver:
    useKubernetesLease: true
  akkaManagementPort: "8558"
  grpcPort: "8101"
  httpPort: "8080"
  prometheusPort: "9001"
  readinessProbe:
    httpGet:
      path: "/ready"
      port: "management"
  livenessProbe:
    httpGet:
      path: "/alive"
      port: "management"
  grpcIngress:
    enabled: true
    certificate: "arn:aws:acm:region:certificate/cert-id"
    class: "alb"
    annotations:
      ingress:
        alb.ingress.kubernetes.io/auth-on-unauthenticated-request: "authenticate"
  httpIngress:
    enabled: true
    certificate: "arn:aws:acm:region:certificate/cert-id"
    class: "alb"
    annotations:
      ingress:
        alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-2016-08"
      service:
        alb.ingress.kubernetes.io/auth-on-unauthenticated-request: "authenticate"
        alb.ingress.kubernetes.io/auth-scope: "openid"
  configSecret:
    secretName: "additional-config"
  envFrom:
  - configMapRef:
      name: "env-configmap"
  - secretRef:
      name: "env-secret"
  logbackSecret:
    secretName: "logback"
  secretVolumes:
  - secretName: "additional-volume1"
    mountPath: "/etc/volume1"
  - secretName: "additional-volume2"
    mountPath: "/etc/volume2"
  extraVolumeMounts:
  - mountPath: "/mnt/example"
    name: "extra-volume-mount"
  javaOptions: "-Dakka.actor.default-blocking-io-dispatcher.thread-pool-executor.fixed-pool-size=10 -Xlog:gc"
  env:
  - name: "DEMO_GREETING"
    value: "Hello from the environment"
  - name: "DEMO_FAREWELL"
    value: "Such a sweet sorrow"
  deploymentStrategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
    type: "RollingUpdate"
  resources:
    limits:
      memory: "512Mi"
    requests:
      memory: "512Mi"
      cpu: "1000m"
  kafka:
    credentialsSecret: "shopping-cart-service-kafka-secret"
    bootstrapServersKey: "bootstrapServers"
  kafkaConfluentCloud:
    credentialsSecret: "shopping-cart-service-kafka-confluent-secret"
    bootstrapServerKey: "bootstrapServer"
    apiKeyKey: "apiKey"
    apiSecretKey: "apiSecret"
  jdbc:
    credentialsSecret: "shopping-cart-service-jdbc-secret"
    connectionUrlKey: "connectionUrl"
    usernameKey: "username"
    passwordKey: "password"
  cassandraDataStaxAstra:
    credentialsSecret: "shopping-cart-service-astra-secret"
    usernameKey: "username"
    passwordKey: "password"
    secureConnectBundleKey: "secureConnectBundle"
  roles:
  - name: "entity"
    replicasRatio: 40
    replicasMin: 2
    replicasMax: 1000
  - name: "projection"
    replicasRatio: 60
    replicasMin: 1
    replicasMax: 10
  podTemplateSpec:
    metadata:
      annotations:
        my-annotation: "my-value"
    spec:
      containers:
      - command:
        - "sh"
        - "-c"
        - "echo hello"
        image: "busybox"
        name: "hello"
  serviceAccount: "my-service-account"
  resolvedAppVersion: "20201124-120910"
