apiVersion: v2
name: akka-operator
description: Akka Operator in Akka Cloud Platform
# Akka Operator
type: application
# This is the chart version, which corresponds to the version of the Akka Operator.
version: 0.4.2
# This is the version number of the Akka Operator, being deployed.
appVersion: 0.4.2
