# Force to use this chart with Helm 3
# https://helm.sh/docs/topics/charts/#the-apiversion-field
apiVersion: v2
name: akka-operator
description: Akka Operator in Akka Cloud Platform
# Akka Operator
type: application
# This is the chart version, which corresponds to the version of the Akka Operator.
version: 1.1.5-0-1bcf6fb6-20210302-1255
# This is the version number of the Akka Operator, being deployed.
appVersion: 1.1.5-0-1bcf6fb6-20210302-1255
