{{ if eq .Values.serviceAccount.name "" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "akka-operator.serviceAccountName" . }}
  labels:
    {{- include "akka-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{ end }}
