{{- if ne .Values.lightbendSubscription.username "false" }}
## This is based on the Helm How-To trick to create image pull secrets (https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets)
apiVersion: v1
kind: Secret
metadata:
  name: commercial-credentials
  labels:
    app.kubernetes.io/component: credentials
type: "kubernetes.io/dockerconfigjson"
data:
  .dockerconfigjson: {{ template "imagePullSubscriptionSecret" . }}

{{- end }}
