{{- if .Values.imageCredentials.username }}
apiVersion: v1
kind: Secret
metadata:
  name: commercial-credentials
  labels:
    app.kubernetes.io/component: credentials
type: "kubernetes.io/dockerconfigjson"
data:
  .dockerconfigjson:  {{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageCredentials.registry (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}

{{- end }}
